### ISSUE TITLE
[Feature Request] Ability to generate only C++ reference, or only Blueprint Reference

### ISSUE THREAD

**Issue by SirLich** [medelfor/surreal-docs#18]
It's possible this already exists, but I couldn't find it.

 I've been checking the documentation here https://docs.medelfor.com/medelfor/surreal-docs/1.0.1/en-US/docs/surreal-json, but if I understand it correctly, all options apply to both targets (i.e., I can prevent a module from generating, but that will effect both the Blueprint and C++ pages).

**Comment by alicewlx** [comment]
Hi @SirLich!

It's not clear what exactly you mean by "generate only X reference". Do you want to prevent HTML files from of not-necessary reference to be created? Or do you refer to the sidebar link to one of the references? Or do you just want there to be no loading/processing of C++ or BP reference?

Regarding `surreal.json`, you can always manually remove all entries from either `filter.cpp.include` or `filter.native_modules.include` to left only one reference.

Please let me know if that helps

**Comment by SirLich** [comment]
By default, two separate API references will be generated:

![image](https://github.com/medelfor/surreal-docs/assets/18729296/0c5404e2-b1a2-44b8-852d-cc51d7b1f9b4)

I would like to have an option which allows me to disable/enable the Blueprint/C++ API generation separately. 

For example, I would like to generate the Blueprint API, without the C++ API. I can try the `filter` fields in the `surreal.json`, but my understanding is that this will prevent documentation from being generated entirely (for both API targets). I will try it though.

**Comment by alicewlx** [comment]
Thank you for clarifying!

The sidebar link can be removed using `contents` in `surreal.json`. The `filter` fields can be used to completely disable generation of one or another references. Note however that in order to maximize quality of resulting documentation Surreal Docs sometimes uses information from native definitions when generating BP reference and vice-versa. So disabling generation of one reference can consequently disable some smart features in the remaining reference.
