### ISSUE TITLE
[Bug] Generate documents failed because of invalid stof argument

### ISSUE THREAD

**Issue by PrimaryFantasty** [medelfor/surreal-docs#2]
# Environment
surrealDoc both 1.0.3 and 1.0.2
Windows 11 x64
UE 5.0.3
Node 18.16.0
Visual Studio 2022 MSVC 14.36.32532
C++ project
# Error message
Log: [generate-cli] [error] Exception in generate thread: invalid stof argument

https://github.com/medelfor/surreal-docs/blob/9864a28cc7467292f2e6963a18d74de04e55d191/module_cli/cli/cli/GenerateCLI.cpp#L49

**Comment by wcobalt** [comment]
Sorry for the inconvenience @PrimaryFantasty !

May I ask, has the error happened on the "Serializing" stage? We identified a place during this stage where the issue could occur and now are building a version with the hotfix. ETA is 1-2 hours

**Comment by wcobalt** [comment]
Hey @PrimaryFantasty !

We've built a version with the potential fix (1.0.3-hotfix1). You can download it from the main page of [medelfor.com](https://medelfor.com). Be sure to try it out and please let us know if the issue is resolved or not.

Note that since it's a very fresh build Windows SmartScreen can be showing warnings about "an unrecognized up".

**Comment by PrimaryFantasty** [comment]
Now 1.0.3-hotfix1 works well in my environment, thank you!

> Sorry for the inconvenience @PrimaryFantasty !
> 
> May I ask, has the error happened on the "Serializing" stage? We identified a place during this stage where the issue could occur and now are building a version with the hotfix. ETA is 1-2 hours

Yes! Now 1.0.3-hotfix1 works well in my environment, thank you very much! 
Your product is wonderful!
